### ISSUE TITLE
**struct `Timestamp` is private** when using uuid 1.2

### ISSUE THREAD

**Issue by UkonnRa** [cksac/fake-rs#103]
Failed to compile using `uuid 1.2`.

```
error[E0603]: struct `Timestamp` is private
  --> C:\Users\57438\.cargo\registry\src\github.com-1ecc6299db9ec823\fake-2.5.0\src\impls\uuid\mod.rs:24:28
   |
24 |         let ts = uuid::v1::Timestamp::from_rfc4122(ticks, counter);
   |                            ^^^^^^^^^ private struct
   |
note: the struct `Timestamp` is defined here
  --> C:\Users\57438\.cargo\registry\src\github.com-1ecc6299db9ec823\uuid-1.2.0\src\v1.rs:6:22
   |
6  | use crate::{Builder, Timestamp, Uuid};
   |                      ^^^^^^^^^

For more information about this error, try `rustc --explain E0603`.
error: could not compile `fake` due to previous error
```
